### ISSUE TITLE
Footer: "IBINEX OFFICES"

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-laravel#12]
I checked my copy of the security/mobile.png and the font color should be R: 98, G: 104, B: 136 or #626888.

Currently we have the following code:
body h1.grey, body h2.grey, body footer .grey {
    color: **#9c9c9c**;
}

@peterbrionibinex Can you check?

**Comment by peterbrionibinex** [comment]
already done doing this

**Comment by AnsellCC** [comment]
@lester-ar-ibinex-tech can you confirm and close the issue if its fixed? Thanks!

**Comment by lester-ar-ibinex-tech** [comment]
Thanks
