### ISSUE TITLE
Footer: "IBINEX OFFICES" capitalization

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-laravel#13]
Under IBINEX OFFICES, iBinex Financials and iBinex technologies should have their first letter "I" updated to lowercase "i".

@peterbrionibinex 
Can you check your own copy since I am basing all these against my own copy only (security folder)?

See snippet.
![image](https://user-images.githubusercontent.com/37060596/37580941-4535c2ea-2b81-11e8-9572-911360eece1f.png)

**Comment by peterbrionibinex** [comment]
small caps iyon.
