### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by peterbrionibinex** [AnsellCC/ibinex-laravel#15]
[Ibinex-Desktop.pdf](https://github.com/AnsellCC/ibinex-laravel/files/1825685/Ibinex-Desktop.pdf)]

Attach is the list of issues that needs to be solved for the website.

**Comment by peterbrionibinex** [comment]
Done fixing my issue. Please see if you have recommendations for this one. Thanks.

**Comment by AnsellCC** [comment]
Please write them down individually per issue so we could track it easily. Thanks @peterbrionibinex  :D

**Comment by peterbrionibinex** [comment]
wait
