### ISSUE TITLE
Favicon not visible enough

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-laravel#18]
**SUGGESTION ONLY**

Might I suggest that we change color of favicon for it to be visible enough for the user. 
Color suggestion: same color as the background color used in the loading animation

See snippet.
![image](https://user-images.githubusercontent.com/37060596/37632545-a52da5c0-2c29-11e8-9f93-43be47fc3ebe.png)

**Comment by AnsellCC** [comment]
Approved and assigned to @jsimpao 

make it color red please #ff0000

**Comment by peterbrionibinex** [comment]
I think all favicons to all pages are not visible enough. I would also suggest that the color of favicon itself must be changed

**Comment by jsimpao** [comment]
Fix pushed to master branch.
