### ISSUE TITLE
Contact Us issues

### ISSUE THREAD

**Issue by peterbrionibinex** [AnsellCC/ibinex-laravel#2]
List of issues that needs to be solved:

1. Some text are not aligned properly and there's no margin on the left side.
https://user-images.githubusercontent.com/37060599/37395898-63f8081e-27b2-11e8-86ef-a38f0d091a42.png
**checked using Galaxy S5, Nexus 5X and 6P, iPhone 7 and 7 Plus, iPhone 8 and iPhone 8 Plus, iPhone X

2. There's no spacing before Get Started title.
https://user-images.githubusercontent.com/37060599/37396084-d9203ddc-27b2-11e8-8cc6-0fd0b5a7d5ae.png
**checked using iPad and iPad Pro.

3. The Contact form is not responsive and it's too small. 
https://user-images.githubusercontent.com/37060599/37395839-343184e8-27b2-11e8-8d8b-d78463f7d994.png
**checked using iPad and iPad Pro.

**Comment by AnsellCC** [comment]
@acelabini

**Comment by peterbrionibinex** [comment]
![contactform](https://user-images.githubusercontent.com/37060599/37395839-343184e8-27b2-11e8-8d8b-d78463f7d994.png)
![supportissue](https://user-images.githubusercontent.com/37060599/37395898-63f8081e-27b2-11e8-86ef-a38f0d091a42.png)

**Comment by peterbrionibinex** [comment]
![getstartedissue](https://user-images.githubusercontent.com/37060599/37396084-d9203ddc-27b2-11e8-8cc6-0fd0b5a7d5ae.png)

**Comment by acelabini** [comment]
@peterbrionibinex retest pls.

**Comment by acelabini** [comment]
@peterbrionibinex done. added min-width

**Comment by peterbrionibinex** [comment]
issue is now closed.
