### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-laravel#27]
Hi @peterbrionibinex 

Can you check again the footer?

Just now I see that the footer layout - alignments bw contents, font sizes, input form, and spaces for the generated and expected outputs are very different. These elements do not have issues yesterday.
See snippets below

Expected:
![image](https://user-images.githubusercontent.com/37060596/37637866-02efbaf2-2c45-11e8-8203-0b17c0837261.png)

Generated:
![image](https://user-images.githubusercontent.com/37060596/37637926-53596a10-2c45-11e8-8b49-2abe9088f917.png)

**Comment by AnsellCC** [comment]
I fixed the button turning gray on some resolutions. @lester-ar-ibinex-tech please check the footer again for inconsistencies with the PSD file

**Comment by peterbrionibinex** [comment]
Already done fixing the footer from reso 992px to 1199px. But, I haven't push it yet
