### ISSUE TITLE
homepage "quotation mark"

### ISSUE THREAD

**Issue by AnsellCC** [AnsellCC/ibinex-laravel#37]
Current:
![quote_current](https://user-images.githubusercontent.com/37060593/37693995-5bd8921a-2cfe-11e8-80d5-f10d55de5a95.PNG)

PSD:
![quote_original](https://user-images.githubusercontent.com/37060593/37693996-5c11db06-2cfe-11e8-9c89-9c2acf65f455.PNG)

**Comment by jovitorrevillas** [comment]
Fixed.
