### ISSUE TITLE
hero_height for PC

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-laravel#7]
###We already established hero_height = 100VH for MOBILE.

Pero dun kasi sa PSD file na ipinakita sakin ni @jovitorrevillas , for PC only HOME and PRICING has hero_height = 100VH, while for the remaining pages, may custom height designated by JoviT.

@AnsellCC @jovitorrevillas Paki clarify naman kung ano talaga dapat ang hero_height for PC?
Thank you!

https://sa1-api.asm.skype.com/v1/objects/0-sa-d1-59aed2a59b530e07857a1e5bffc2007a/views/imgpsh_fullsize

**Comment by AnsellCC** [comment]
According to the designer, stick with the PSD so hindi full height sa PC ung ibang pages. Basta 1:1 dapat daw kung gaano itsura sa PSD ganun rin dapat
